# Generated by Django 6.1 on 2026-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="clause",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
