# Generated by Django 6.1 on 2026-08-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0002_documentchunk_clause"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
