# Generated by Django 6.1 on 2026-08-29 14:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistence",
            "0003_document_content_hash_document_embedding_provider_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
