# Generated by Django 6.1 on 2026-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0004_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="search_content",
            field=models.TextField(blank=True),
        ),
    ]
