# Generated by Django 6.1 on 2026-08-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0005_documentchunk_search_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyversion",
            name="deductible",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="policyversion",
            name="policy_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
