# Generated by Django 6.1 on 2026-08-31 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0006_policyversion_deductible_policyversion_policy_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="persistence.job",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="persistence.job",
            ),
        ),
    ]
