# Generated by Django 6.1 on 2026-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0007_approval_job_decision_job"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobstep",
            constraint=models.UniqueConstraint(
                fields=("job", "name"), name="unique_job_step_per_job"
            ),
        ),
    ]
