# Generated by Django 6.1 on 2026-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0008_jobstep_unique_job_step_per_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
