# Generated by Django 6.1 on 2026-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0009_agentrun_correlation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
