# Generated by Django 6.1 on 2026-09-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0010_agentrun_input_tokens_agentrun_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="final_payout",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="final_payout",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
