from django.urls import path

from presentation.api.sse import job_progress_stream
from presentation.api.views import (
    AdjudicateView,
    ApprovalDecisionView,
    AskView,
    CancelJobView,
    ClaimDetailView,
    ClaimListView,
    ClientListView,
    CreateAdjusterView,
    CreateClaimView,
    CurrentUserView,
    DocumentListView,
    DocumentStatusView,
    HealthView,
    JobStatusView,
    JobTraceView,
    PolicyUploadView,
    PolicyVersionListView,
    ReadinessView,
)

urlpatterns = [
    path("adjudicate/", AdjudicateView.as_view(), name="adjudicate"),
    path("jobs/<uuid:job_id>/", JobStatusView.as_view(), name="job-status"),
    path("jobs/<uuid:job_id>/stream/", job_progress_stream, name="job-progress-stream"),
    path("jobs/<uuid:job_id>/cancel/", CancelJobView.as_view(), name="job-cancel"),
    path("users/adjusters/", CreateAdjusterView.as_view(), name="create-adjuster"),
    path("auth/me/", CurrentUserView.as_view(), name="current-user"),
    path("policies/upload/", PolicyUploadView.as_view()),
    path("documents/", DocumentListView.as_view(), name="document-list"),
    path("documents/<uuid:document_id>/", DocumentStatusView.as_view()),
    path("claims/",ClaimListView.as_view(), name="claim-list"),
    path("claims/<uuid:claim_id>/", ClaimDetailView.as_view(), name="claim-detail"),
    path("claims/<uuid:claim_id>/ask/", AskView.as_view(), name="ask"),
    path("jobs/<uuid:job_id>/approve/", ApprovalDecisionView.as_view(), name="approve"),
    path("jobs/<uuid:job_id>/trace/", JobTraceView.as_view(), name="job-trace"),
    path("health/", HealthView.as_view()),
    path("health/ready/", ReadinessView.as_view()),
    path("claims/create/", CreateClaimView.as_view(), name="create-claim"),
    path("clients/", ClientListView.as_view(), name="client-list"),
    path("policy-versions/", PolicyVersionListView.as_view(), name="policy-version-list"),
]